### ISSUE TITLE
[feature] 关于支持 hint file

### ISSUE THREAD

**Issue by PedroGao** [roseduan/rosedb#12]
hint file 是 bitcask 中对于启动时，建立索引的一种优化手段。
如果 db 存在大量的数据文件，那么再次打开 db 时，必须重新扫描所有数据文件重建索引，这样的效率是十分低下的，因此 bitcask 提出了 hint file 保存索引文件来帮助 db 进行快速启动。

本人自告奋勇想为 rosedb 实现 hint file 这个 feature，故开此 issue 来听取大家意见，为 rosedb 略尽绵薄之力。

**Comment by roseduan** [comment]
非常感谢，这是很重要的功能，也是迟早会实现的。
需要注意一点，由于 rosedb 支持多种数据结构，所以对于 List、Hash、Set、ZSet 的 hint file 存储，可能需要多多考虑和构思一下。
还有生成 hint file 的时机，以及file占用空间的大小，需要预估一下。

**Comment by PedroGao** [comment]
对于 rosedb，hint file 有些麻烦，由于 rosedb 支持多种数据结构，hint file 的 entry 无法很好工作，这还需要更多的调研和研究
