### ISSUE TITLE
A milestone!

### ISSUE THREAD

**Issue by roseduan** [roseduan/rosedb#17]
rosedb has reached 1k stars after first commit in 2020.12.06 👏
This is awesome, thanks for your support, I will continue to do it better.

**Comment by a592988978** [comment]
great job！

**Comment by sddwt** [comment]
congratulations!

**Comment by YanniHu1996** [comment]
cool~

**Comment by Abeautifulsnow** [comment]
Congratulation!!! You made it 👍

**Comment by taiyang-li** [comment]
Congratulation!!!
