### ISSUE TITLE
求该项目的参考论文

### ISSUE THREAD

**Issue by ByteFlyCoding** [roseduan/rosedb#2]
我在B站上刷到你的视频，对这个项目非常感兴趣，能不能在readme里面添加上你这个项目的参考论文，我挺想拜读一下源论文的，万分感谢。

**Comment by dengyunsheng250** [comment]
同

**Comment by roseduan** [comment]
sorry 回复晚了，论文在这里：
https://riak.com/assets/bitcask-intro.pdf

**Comment by piao88** [comment]
从b站匆匆赶来，up主加油！期待你视频的更新，我近期也会好好研究下代码，争取完成几个issue

**Comment by ByteFlyCoding** [comment]
> sorry 回复晚了，论文在这里：
> https://riak.com/assets/bitcask-intro.pdf

Thank you, Let's make progress together.
