### ISSUE TITLE
这里使用map结构标志list中哪些value存在，是否意味着rosedb中的list目前还不能包含重复value

### ISSUE THREAD

**Issue by taiyang-li** [roseduan/rosedb#30]
https://github.com/roseduan/rosedb/blob/3041bb3677c5405758adbf2f73d913e6830bbc62/ds/list/list.go#L30

**Comment by roseduan** [comment]
支持的，实际存储是在 Record 的链表中，values 只是为了记录链表的 value 是否存在。
