### ISSUE TITLE
性能有点差

### ISSUE THREAD

**Issue by dongdongwcpp** [roseduan/rosedb#46]
![image](https://user-images.githubusercontent.com/85050932/134124418-c8aef6b8-8971-40a2-84cc-d1fcf43c1306.png)

作为无序hashtable storage engine，速度应该可以更快的

**Comment by roseduan** [comment]
有测过 rocksdb 吗，能达到多少

**Comment by dongdongwcpp** [comment]
在我的机械硬盘，特别调参后，210MB/s avg

**Comment by roseduan** [comment]
嗯嗯，目前还没有做压缩。
你的 no duplicate key ，no delete 场景的确比较适合 bitcask 模型
