### ISSUE TITLE
关于将list、set、hash、zset 接口支持interface的问题

### ISSUE THREAD

**Issue by FitzLong** [roseduan/rosedb#69]
如果希望list、set、hash、zset 接口支持interface， 那么是否需要在编码函数即EncodeValue函数中，支持多类型的编码，同时在list、set、hash、zset 的结构体内将支持String的结构 修改为 interface{} 结构 ？

**Comment by roseduan** [comment]
目前使用的是 msgpack，传参进来统一装换成 []byte。
Get Value 的时候，需要传对应的值进行转换，可以参考 String 接口
